'''failure cases'''
parallel5 = 'p5'
parallel8 = 'p8'
direct5 = 'd5'
direct8 = 'd8'
repeated_note = 'R'
tritone = 'ag4'
middle_tritone = 'mTR'
isolated_tritone = 'iTR'
bad_ending = 'bE'
sixthM = '6M'
badJump = 'j'
seq = 'SQ'
pairs = 'ABAB'
bad_movement = 'bM'
bad_start = 'bS'
dissonance = 'dS'
